### ISSUE TITLE
Restart command is set as true, yet doesn't restart server?

### ISSUE THREAD

**Issue by ff-hjarvis** [Bridgewater/appetite#15]
Everything else of appetite works, however I am tired of having to manually restart the server every time there is a change. Whenever a change is made and run_appetite.sh is run, the output says the restart of the server is true, as is written in the apps.conf file. However, when I open the server it does not restart at all. It seems that all of the commands.conf commands do not work. I am sure I have Jinja2 as well and the correct version. What can I do?

Thanks, 
ff-hjarvis

**Comment by kalpatel01** [comment]
Sounds like it might be a paramiko problem (The library that actually makes the ssh connections), What version of paramiko are you using?
`pip show paramiko`

**Comment by ff-hjarvis** [comment]
The information of paramiko is as follows:
/usr/local/bin/pip show paramiko
Name: paramiko
Version: 2.4.1
Summary: SSH2 protocol library
Home-page: https://github.com/paramiko/paramiko/
Author: Jeff Forcier
Author-email: jeff@bitprophet.org
License: LGPL
Location: /usr/local/lib/python2.7/site-packages
Requires: cryptography, pynacl, pyasn1, bcrypt
Required-by: scp

**Comment by kalpatel01** [comment]
I had problems with newer versions, I had to lock the version.
I have a PR coming up that should fix this.
You should lock pip versions:
src/requirements.txt
    setuptools
    Jinja2==2.8
    paramiko==2.0.2
    scp==0.10.2
    pyyaml==3.12

**Comment by ff-hjarvis** [comment]
They are all on the oldest version now, however the restart still isn't working. The only strange thing is that it seems to try to load a file called meta_repo.json and it strangely checks for connection, which didn't happen before: 

{"error": "'unicode' object has no attribute 'items'", "msg": "Problems loading meta file", "path": "/tmp/repo/meta/splunk-ds001-0c/appetite/meta_repo.json"}
{"cmd": "echo checking_connection", "hostname": "splunk-ds001-0c", "module": "buildin_function", "msg": "run_cmd", "output": {"function": "run_cmd", "rc": 0, "stderror": "", "stdout": "checking_connection\r\n"}}

Any suggestions?
Thanks for the help, hjarvis

**Comment by kalpatel01** [comment]
It does that connection check since there is no point of trying to install anything if it can not connect.  Looks like the above connected correctly.  Appetite will try to pull down meta files (appetite source of truth) if it doesn't exist.  This is incase the scratch directory is blown away.  If it doesn't find the file to it installs all the apps from the manifest for the host and need be bootstrap apps.  Check the logs, there should be something about a restart.

**Comment by ff-hjarvis** [comment]
In the logs for appetite, I obtain the following:

{"status": "added", "is_firstrun": false, "updated": true, "content_type": "list", "track": {"process_datetime": "2018-07-27T19:15:11.848340Z", "push_abbrev_commit_id": "26a6ebf", "version": "1.1.170207", "uid": "62513948-91d1-11e8-a664-0e884a0bf715", "push_commit_id": "26a6ebfba72352000ef04031beec67773cd79cbc"}, "app": "Splunk_Operations", "app_creation_datetime": "2018-07-27T19:15:25.370887Z", "commit_log": {"body": "", "project": "git@github.com:ff-hjarvis", "committer_email": "noreply@github.com", "author_email": "40272147+ff-hjarvis@users.noreply.github.com", "author_name": hjarvis", "app_abbrev_commit_id": "20d7185", "reponame": "splunk-operations-app", "app_commit_id": "20d7185d3e5bef7cac5d4effc0f421bdb1b4e2b2", "committer_name": "GitHub", "commit_notes": "", "subject":  App Deployment test"}, "source_hostname": "splunk-ds001-0c", "repo_source": "repo", "method_info": {"commands": [], "name": "StandAlone", "skip_templating": false, "delete_first": false, "update_method": "copy", "run_first_script": [], "all_sites": false, "path": "/opt/splunk/etc/apps/", "run_last_script": [], "install_ignore": ["lookups/", "metadata/local.meta", "local/"], "restart": true, "no_appetite_changes": false}, "app_clean": "Splunk_Operations"}

It doesn't look like anything is wrong, and again the app is getting updated each time, it is evident in the files. Yet the server doesn't restart. Could it be a permissions issue? The ssh user that I am using is not the root user of the remote server, however appetite has problems running with root being the user. 

The other log file just talks about the meta_repo.json error and how it has problems loading.

Thanks,
hjarvis

**Comment by kalpatel01** [comment]
Might be the problem.  It tack's a sudo at the beginning of the command.  Do you need root with your SSH user to run restart?  The actual restart command with stdout should be in the logs.
